# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0002_goal_goal_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_setter',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_status',
            field=models.IntegerField(default=1),
        ),
    ]
