# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0003_auto_20160630_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goalapp.User'),
        ),
    ]
