# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0004_goal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
    ]
