# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0007_auto_20161009_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_funds',
            field=models.IntegerField(default=0),
        ),
    ]
