# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0009_auto_20161012_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder', models.CharField(max_length=50)),
                ('funder_email', models.EmailField(max_length=254)),
                ('funded_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funder', to='goalapp.Goal')),
            ],
        ),
    ]
